import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

type DotnetVersion = 'net8.0' | 'net9.0' | 'net10.0';
type Architecture = 'clean' | 'nlayered' | 'vertical-slice';

export interface DotnetGeneratorOptions {
    projectName: string;
    targetFramework: DotnetVersion;
    architecture: Architecture;
    destination: string;
}

function isValidProjectName(name: string): boolean {
    return /^[A-Za-z_][A-Za-z0-9_.]*$/.test(name);
}

async function runDotnet(args: string[], cwd: string): Promise<void> {
    try {
        await execFileAsync('dotnet', args, {
            cwd,
            windowsHide: true,
            maxBuffer: 10 * 1024 * 1024,
        });
    } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`dotnet ${args.join(' ')} failed: ${message}`);
    }
}

async function ensureDotnetInstalled(): Promise<string> {
    try {
        const { stdout } = await execFileAsync('dotnet', ['--version'], { windowsHide: true });
        return stdout.trim();
    } catch {
        throw new Error('The .NET SDK was not found. Install the .NET SDK and make sure "dotnet" is available in PATH.');
    }
}

async function createFolders(projectRoot: string, folders: string[]): Promise<void> {
    await Promise.all(folders.map((folder) => fs.mkdir(path.join(projectRoot, folder), { recursive: true })));
}

async function pathExists(target: string): Promise<boolean> {
    try {
        await fs.access(target);
        return true;
    } catch {
        return false;
    }
}

async function findSolutionFile(projectRoot: string, projectName: string): Promise<string> {
    const entries = await fs.readdir(projectRoot, { withFileTypes: true });
    const solution = entries.find((entry) => entry.isFile() && (entry.name.endsWith('.sln') || entry.name.endsWith('.slnx')));
    if (!solution) throw new Error(`Could not find the generated solution file for ${projectName}.`);
    return solution.name;
}

async function prepareProjectRoot(options: DotnetGeneratorOptions): Promise<{
    projectRoot: string;
    solutionFile: string;
    src: string;
}> {
    if (!isValidProjectName(options.projectName)) {
        throw new Error('Invalid project name. Use letters, numbers, underscores, and dots only, starting with a letter or underscore.');
    }

    await ensureDotnetInstalled();
    const projectRoot = path.resolve(options.destination, options.projectName);
    if (await pathExists(projectRoot)) {
        throw new Error(`A folder named "${options.projectName}" already exists at the selected location.`);
    }

    const src = path.join(projectRoot, 'src');
    await fs.mkdir(src, { recursive: true });
    await runDotnet(['new', 'sln', '--name', options.projectName], projectRoot);
    const solutionFile = await findSolutionFile(projectRoot, options.projectName);
    return { projectRoot, solutionFile, src };
}

async function createProject(
    template: string,
    name: string,
    framework: DotnetVersion,
    cwd: string,
    extraArgs: string[] = [],
): Promise<void> {
    await runDotnet(['new', template, '--name', name, '--framework', framework, ...extraArgs], cwd);
}

async function addProjectsToSolution(
    projectRoot: string,
    solutionFile: string,
    projects: string[],
): Promise<void> {
    for (const project of projects) {
        await runDotnet(['sln', solutionFile, 'add', project], projectRoot);
    }
}

async function finalizeProject(projectRoot: string, solutionFile: string, projectName: string, architecture: string): Promise<void> {
    await runDotnet(['restore', solutionFile], projectRoot);
    await runDotnet(['build', solutionFile, '--no-restore'], projectRoot);

    const readme = `# ${projectName}\n\nGenerated by Backend Structure Generator.\n\n## Architecture\n\n${architecture}\n\n## Build\n\nThe solution was restored and built successfully during generation.\n`;
    await fs.writeFile(path.join(projectRoot, 'README.md'), readme, 'utf8');
}

export async function generateDotnetCleanArchitecture(options: DotnetGeneratorOptions): Promise<string> {
    const { projectRoot, solutionFile, src } = await prepareProjectRoot(options);
    const api = `${options.projectName}.Api`;
    const application = `${options.projectName}.Application`;
    const domain = `${options.projectName}.Domain`;
    const infrastructure = `${options.projectName}.Infrastructure`;

    await createProject('webapi', api, options.targetFramework, src, ['--use-controllers']);
    await createProject('classlib', application, options.targetFramework, src);
    await createProject('classlib', domain, options.targetFramework, src);
    await createProject('classlib', infrastructure, options.targetFramework, src);

    await addProjectsToSolution(projectRoot, solutionFile, [
        path.join('src', api, `${api}.csproj`),
        path.join('src', application, `${application}.csproj`),
        path.join('src', domain, `${domain}.csproj`),
        path.join('src', infrastructure, `${infrastructure}.csproj`),
    ]);

    await runDotnet(['add', path.join('src', application, `${application}.csproj`), 'reference', path.join('src', domain, `${domain}.csproj`)], projectRoot);
    await runDotnet(['add', path.join('src', infrastructure, `${infrastructure}.csproj`), 'reference', path.join('src', application, `${application}.csproj`), path.join('src', domain, `${domain}.csproj`)], projectRoot);
    await runDotnet(['add', path.join('src', api, `${api}.csproj`), 'reference', path.join('src', application, `${application}.csproj`), path.join('src', infrastructure, `${infrastructure}.csproj`)], projectRoot);

    await createFolders(path.join(src, api), ['Controllers', 'Middleware', 'Extensions']);
    await createFolders(path.join(src, application), ['DTOs', 'Interfaces', 'Services', 'Features', 'Mappings']);
    await createFolders(path.join(src, domain), ['Entities', 'Enums', 'Exceptions', 'Interfaces', 'ValueObjects']);
    await createFolders(path.join(src, infrastructure), ['Data', 'Repositories', 'Services', 'Configurations', 'Migrations']);

    await fs.rm(path.join(src, api, 'WeatherForecast.cs'), { force: true });
    await fs.rm(path.join(src, api, 'Controllers', 'WeatherForecastController.cs'), { force: true });
    await finalizeProject(projectRoot, solutionFile, options.projectName, 'Clean Architecture');
    return projectRoot;
}

export async function generateDotnetNLayeredArchitecture(options: DotnetGeneratorOptions): Promise<string> {
    const { projectRoot, solutionFile, src } = await prepareProjectRoot(options);
    const api = `${options.projectName}.Api`;
    const business = `${options.projectName}.Business`;
    const data = `${options.projectName}.Data`;
    const models = `${options.projectName}.Models`;

    await createProject('webapi', api, options.targetFramework, src, ['--use-controllers']);
    await createProject('classlib', business, options.targetFramework, src);
    await createProject('classlib', data, options.targetFramework, src);
    await createProject('classlib', models, options.targetFramework, src);

    await addProjectsToSolution(projectRoot, solutionFile, [
        path.join('src', api, `${api}.csproj`),
        path.join('src', business, `${business}.csproj`),
        path.join('src', data, `${data}.csproj`),
        path.join('src', models, `${models}.csproj`),
    ]);

    await runDotnet(['add', path.join('src', business, `${business}.csproj`), 'reference', path.join('src', models, `${models}.csproj`)], projectRoot);
    await runDotnet(['add', path.join('src', data, `${data}.csproj`), 'reference', path.join('src', business, `${business}.csproj`), path.join('src', models, `${models}.csproj`)], projectRoot);
    await runDotnet(['add', path.join('src', api, `${api}.csproj`), 'reference', path.join('src', business, `${business}.csproj`), path.join('src', data, `${data}.csproj`), path.join('src', models, `${models}.csproj`)], projectRoot);

    await createFolders(path.join(src, api), ['Controllers', 'Middleware', 'Extensions']);
    await createFolders(path.join(src, business), ['Services', 'Interfaces', 'DTOs', 'Mappings']);
    await createFolders(path.join(src, data), ['Data', 'Repositories', 'Configurations', 'Migrations']);
    await createFolders(path.join(src, models), ['Entities', 'Enums', 'DTOs']);

    await fs.rm(path.join(src, api, 'WeatherForecast.cs'), { force: true });
    await fs.rm(path.join(src, api, 'Controllers', 'WeatherForecastController.cs'), { force: true });
    await finalizeProject(projectRoot, solutionFile, options.projectName, 'N-Layered Architecture');
    return projectRoot;
}

export async function generateDotnetVerticalSliceArchitecture(options: DotnetGeneratorOptions): Promise<string> {
    const { projectRoot, solutionFile, src } = await prepareProjectRoot(options);
    const api = `${options.projectName}.Api`;

    await createProject('webapi', api, options.targetFramework, src, ['--use-controllers']);
    await addProjectsToSolution(projectRoot, solutionFile, [path.join('src', api, `${api}.csproj`)]);

    await createFolders(path.join(src, api), [
        'Features',
        'Features/Auth',
        'Features/Users',
        'Features/Products',
        'Features/Shared',
        'Common',
        'Common/Behaviors',
        'Common/Exceptions',
        'Common/Middleware',
    ]);

    await fs.rm(path.join(src, api, 'WeatherForecast.cs'), { force: true });
    await fs.rm(path.join(src, api, 'Controllers', 'WeatherForecastController.cs'), { force: true });
    await finalizeProject(projectRoot, solutionFile, options.projectName, 'Vertical Slice Architecture');
    return projectRoot;
}
